### PR TITLE
Re-added atan2/hypot function

### PR DESCRIPTION
**Pull request by henkmuller**

### CODE REVIEW

**Comment by henkmuller** [comment]
This now contains a new FFT - (10-15% faster, bit smaller) in addition to the atan2(), in addition to the acos() and asin().

**Comment by xross** [comment]
Please could someone review (and ideally accept) I'm waiting for the FFT updates

**Comment by johned0** [comment]
I can, Ross

**Comment by johned0** [comment]
All look good to me. Apps build and run correctly.
Minor suggestion : I'd put app_atan2_hypot code in app_math for consistency.
Docs need updating for new functionality. I'm not sure what the protocol is for accepting undocumented updates so I'll leave someone more enlightened to decide whether or not this pull request can be accepted. If it is a blocker, I can try to find some time later today or tomorrow to document.
J

**Pull request merged**
