### PR TITLE
Merge develop into release/v6.0.2

### PR DESCRIPTION
**Pull request by lucianomartin**

### CODE REVIEW

**Review by mbanth — COMMENTED** [review]
The code changes all look good.  The name of the release branch is misleading.

**Comment by lucianomartin** [comment]
> The code changes all look good. The name of the release branch is misleading given that the new version number is 6.0.2.

Thanks for pointing it out. I will delete the branch and create one with the correct name

**Comment by lucianomartin** [comment]
> > The code changes all look good. The name of the release branch is misleading given that the new version number is 6.0.2.
> 
> Thanks for pointing it out. I will delete the branch and create one with the correct name

I have actually just created a release/v6.0.2 branch

**Review by mbanth — APPROVED** [review]
The code changes look good.

**Comment by mbanth** [comment]
Looks like some trouble with the view file name.

**Comment by lucianomartin** [comment]
Close PR to fix failing check

**Pull request closed without merging**
