### PR TITLE
Add Jenkins file, build passing

### PR DESCRIPTION
**Pull request by oscarbailey-xmos**

### CODE REVIEW

**Comment by oscarbailey-xmos** [comment]
Hi @samchesney, the App Notes stage is now working but I had to call xcoreAllAppsBuild rather than xcoreAppNoteBuild.

**Comment by samchesney** [comment]
Ah, that's interesting, I guess this is because the layout of this repo is different to all the others.
We still need to ensure that the documentation is in a working state, perhaps a simple solution for now would be to call `runXdoc(<path to rst dir>)` after all the apps have been built?

**Comment by samchesney** [comment]
👍

**Comment by samchesney** [comment]
Superseded by #125.

**Pull request closed without merging**
