### PR TITLE
DO NOT MERGE: Additional functions required for a RCNN

### PR DESCRIPTION
**Pull request by ThomasGmeinder**

### CODE REVIEW

**Comment by ThomasGmeinder** [comment]
Approve to unblock merging

**Comment by ThomasGmeinder** [comment]
Accidentally closed. Reason for this pull request is to get the tests run on Jenkins flow.

**Comment by johned0** [comment]
Hi Thomas, what is the latest status of this ?
Looks like it just requries the license updating.
Do you want it reviewed and merged ?
J

**Comment by ThomasGmeinder** [comment]
Closing to help XVF3510 release.

**Pull request closed without merging**
