### PR TITLE
Fix vector absolute value function

### PR DESCRIPTION
**Pull request by mbanth**
The dsp_vector_abs() function previously did not convert negative vector elements to a positive in some cases.  The test used to check its operation expected a negative value when it should have expected a positive one.

### CODE REVIEW

**Comment by andrewstanfordjason** [comment]
What happens when x = INT32_MIN?
-x != INT32_MAX.

**Review by andrewstanfordjason — CHANGES_REQUESTED** [review]
I don't think this works for int_min

**Review by andrewstanfordjason — CHANGES_REQUESTED** [review]
it's not efficient or easy maintain but seems functionally correct. I'm not a fan of inline assembly, I'd rather see: 
void dsp_vector_foo( ...){
for (int e=0;e<vl; e++) x[e] = foo(x[e]);
}
for example as speed isn't an issue.

**Comment by mbanth** [comment]
> I'm not a fan of inline assembly, ...

Neither am I.  As far as I can see, the only benefit from the inline assembly in `dsp_vector_negate()` and `dsp_vector_abs()` comes from the load double and store double operators.  Many functions within dsp_vector.c use these operators.  I'm willing to replace the inline assembly in these two functions as you suggest, but will not go beyond that at this point in time.

**Review by andrewstanfordjason — APPROVED** [review]

**Review by shuchitak — APPROVED** [review]
While this is going to increase the functions cycles substantially (if check within innermost loop) I do think this is a necessary change to make the code functionally correct. It helps that none of the audio pipelines core functions seem to be calling dsp_vector_abs/negate so shouldn't have a MIPS impact.

**Pull request merged**
