### PR TITLE
faster, smaller biquad with test

### PR DESCRIPTION
**Pull request by andrewstanfordjason**

### CODE REVIEW

**Comment by johned0** [comment]
Thanks ASJ, Looks good but CI tests failing. Looks like @samchesney might have fixed this here : https://github.com/xmos/lib_dsp/pull/129/files/99ef76eb98ffeb55c70728dca32453e3c8c1a5fe..b5924ed5ecd124897f80936361f8130955dc2559.
@samchesney do you know how to re-run the checks ?

**Comment by samchesney** [comment]
> Thanks ASJ, Looks good but CI tests failing. Looks like @samchesney might have fixed this here : https://github.com/xmos/lib_dsp/pull/129/files/99ef76eb98ffeb55c70728dca32453e3c8c1a5fe..b5924ed5ecd124897f80936361f8130955dc2559.
> @samchesney do you know how to re-run the checks ?

#129 is unrelated, and not intended to fix the failures seen here.

The reason the CI tests are failing on this PR are as follows:
```
[tests] Running shell script
+ ./runtests.py --junit-output=lib_dsp_tests.xml
...
------------
TEST SUMMARY
------------
...
lib_dsp::simple_tests::app_design                                                FAIL
...
lib_dsp::simple_tests::app_filters                                               FAIL
...
------------
66/68 PASSED
------------
```
See the [test results for this PR on Jenkins](http://srv-bri-jcim0:8080/blue/organizations/jenkins/XMOS%2Flib_dsp/detail/PR-130/3/tests) for details on the cause of these failures.

**Comment by johned0** [comment]
Code giving an exception in dsp_filters_biquads().
ASJ - I'm happy to re-review when fixed.

**Comment by andrewstanfordjason** [comment]
No, I did it wrong and as expected it failed. I'm updating it now.

**Comment by johned0** [comment]
"xwaf configure build" has failed:
"Unity repo not found in workspace"
I'm not sure what that means. I'll research it.

**Pull request merged**
