### PR TITLE
Bug fixed dsp_vector_mulv_addv()

### PR DESCRIPTION
**Pull request by johned0**
Also tidied up the example app

### CODE REVIEW

**Comment by henkmuller** [comment]
Should the test output be fixed?

**Comment by johned0** [comment]
If you mean the expect file, Henk, then yes.
I can do that

**Comment by henkmuller** [comment]
Yeah - otherwise the regression will break I think?

**Comment by johned0** [comment]
Agreed, .expect updated in pull request

**Comment by johned0** [comment]
Thanks for merging

**Pull request merged**
